name: nekonata_core
publish_to: "none"

environment:
  sdk: ^3.10.0

workspace:
  - packages/nekonata_location_fetcher
  - packages/nekonata_map
  - packages/nekonata_firestore
  - packages/nekonata_lint
  - packages/nekonata_reporter

dev_dependencies:
  very_good_analysis: ^10.1.0
