name: nekonata_lint_test
description: "A new Flutter plugin project."
version: 0.0.1
environment:
  sdk: ^3.10.0

dependencies:
  auto_route:
  flutter:
    sdk: flutter

dev_dependencies:
  auto_route_generator:
  build_runner:
  custom_lint:
  nekonata_lint:
    path: ../nekonata_lint
  very_good_analysis:
